config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #
  # Rutas para usuario
  get '/empleados' => 'empleados#index'
  get '/new/empleado' => 'empleados#new', as: :newEmpleado
  post '/new/empleado' => 'empleados#create'
  delete 'empleado/:id' => 'empleados#destroy', as: :delete
  get 'empleado/:id/edit' => 'empleados#edit', as: :editEmpleado
  patch 'empleado/:id/update' => 'empleados#update', as: :updateEmpleado

  #Rutas para producto
  get '/productos' => 'productos#index'
  get '/new/producto' => 'productos#new', as: :newProducto
  post '/new/producto' => 'productos#create'
  delete 'producto/:id' => 'productos#destroy', as: :deleteProducto
  get 'producto/:id/edit' => 'productos#edit', as: :editProducto
  patch 'producto/:id/update' => 'productos#update', as: :updateProducto

  #Ruta de Sessiones
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  #Manejo de la Cabecera para Transaccion
  get '/transferencia' => 'transferencia_cabs#new'
  get '/transferencianext' =>'transferencia_cabs#seleccion'
  post '/transferencianext' => 'transferencia_cabs#create', as: :newTransferenciaCab
  get '/Mensaje' => 'transferencia_cabs#mensaje'

  #Solicitudes
  get '/listadesolicitudes' => 'solicitudes#index'
  delete 'solicitud/:id' => 'solicitudes#destroy'
  patch '/transferenciaUpdate' => 'solicitudes#update', as: :updateTransferencia

  root 'sessions#new'
end

app/controllers/solicitudes_controller.rb
class SolicitudesController < ApplicationController
  def index
    @solicitudes= TransferenciaCab.all.includes(:empleado).where(Estatus: "Abierto")
      @solicitud = TransferenciaCab.find_by(@solicitud)
  end
  def update
    @solicitud =TransferenciaCab.find_by(@solicitud)
    if @solicitud.update(params_update)
      redirect_to '/listadesolicitudes', flash: {notice: 'Datos actualizados correctamente'}
    else
      render 'solicitudes/index', flash: {notice: 'Error en actualizar registro'}
    end
  end

def destroy
  @solicitud = TransferenciaCab.find(params[:id])
  if @solicitud.destroy
    redirect_to '/listadesolicitudes',flash: { notice3: 'Solicitud eliminada correctamente '}
  else
    redirect_to '/listadesolicitudes',flash: { notice4: 'La Solicitud no pudo ser eliminada'}
  end
end

  private
  def params_detalle
    params.require(:transferenica_det).permit(:TransferenciaCab_id,:Servicio,:producto_id,:Estatus,:Tiempo)
  end

  def params_update
    params.require(:transferencia_cab).permit(:Estatus)
  end
end

app/helpers/solicitudes_helper.rb
module SolicitudesHelper
end

app/views/solicitudes/index.html.erb
<nav class="sidebar-navigation">
  <ul>
    <%=link_to empleados_path do %>
      <li >
        <i class="fa fa-users" aria-hidden="true"></i>
        <span class="tooltip">Lista de Empleados</span>
      </li>
    <%end %>

    <%=link_to productos_path do %>
      <li class="active" >
        <i class="fa fa-folder-open " aria-hidden="true"></i>
        <span class="tooltip">Lista de Productos </span>
      </li>
    <%end %>


    <%=link_to listadesolicitudes_path do %>
      <li >
        <i class="fa fa-address-book-o" aria-hidden="true"></i>
        <span class="tooltip">Lista de solicitudes </span>
      </li>
    <%end %>

    <%=link_to empleados_path do %>
      <li >
        <i class="fa fa-pie-chart" aria-hidden="true"></i>
        <span class="tooltip">Reportes </span>
      </li>
    <%end %>
  </ul>
</nav>

<header class="header-nav">
  <div class="perfil">
    <p class="parrafo"><strong>Bienvenido :  </strong><%=current_user.userCompleto%></p>
    <span class="perfil--close"> <%=link_to 'Cerrar sesion',  logout_path, method: :delete,class: 'link' %></span>
  </div>
</header>


<div class="container--box">
  <header class="header-title">
    <h1>Lista de Espera</h1>
  </header>
  <% if @solicitudes.empty? %>
    <h2>No hay solicitudes registradas aun... </h2>



  <%else %>
    <div class="container--tableEmpl">

      <table class="ui very basic collapsing celled table table--empl">
        <thead>
        <tr>
          <th>Numero</th>
          <th>Nombre Empleado</th>
          <th>Servicio</th>
          <th>Seleccion</th>
          <th>Accion</th>
        </tr></thead>
        <tbody>
        <%@solicitudes.each do |e| %>
          <tr>
            <td><%=e.id %></td>
            <td><%=e.empleado.Nombre%></td>
            <td><%=e.Servicio %></td>
            <td>
              <%= form_for  @solicitud, url: updateTransferencia_path(@solicitud) do |f| %>
              <%= f.select :Estatus, options_for_select([["Seleccionar", ""], "Almacen", "Despachar"])  %>
            </td>
            <td colspan="3">
              <%= f.submit 'Aceptar', class: "btn btn-warning" %>
              <%end %>
              <%= link_to 'Descartar', { action: :destroy, id: e.id }, method: :delete, class: "btn btn-danger",data: {confirm: "Esta seguro de eliminar esta solicitud"} %>
            </td>
          </tr>
        <%end %>
        </tbody>
      </table>
    </div>
  <%end %>
</div>
<%if flash[:notice]%>
  <div class="alert alert-info" style="float: right; margin-right: 500px">

    <p><%= flash[:notice]%></p>

  </div>
<%end %>

<%if flash[:notice2]%>
  <div class="alert alert-success" style="float: right; margin-right: 500px">

    <p><%= flash[:notice2]%></p>

  </div>
<%end %>

<%if flash[:notice3]%>
  <div class="alert alert-success" style="float: right; margin-right: 500px">

    <p><%= flash[:notice3]%></p>

  </div>
<%end %>