config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #
  # Rutas para usuario
  get '/empleados' => 'empleados#index'
  get '/new/empleado' => 'empleados#new', as: :newEmpleado
  post '/new/empleado' => 'empleados#create'
  delete 'empleado/:id' => 'empleados#destroy', as: :delete
  get 'empleado/:id/edit' => 'empleados#edit', as: :editEmpleado
  patch 'empleado/:id/update' => 'empleados#update', as: :updateEmpleado

  #Rutas para producto
  get '/productos' => 'productos#index'
  get '/new/producto' => 'productos#new', as: :newProducto
  post '/new/producto' => 'productos#create'
  delete 'producto/:id' => 'productos#destroy', as: :deleteProducto
  get 'producto/:id/edit' => 'productos#edit', as: :editProducto
  patch 'producto/:id/update' => 'productos#update', as: :updateProducto

  #Ruta de Sessiones
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  #Manejo de la Cabecera para Transaccion
  get '/transferencia' => 'transferencia_cabs#new'
  get '/transferencianext' =>'transferencia_cabs#seleccion'
  post '/transferencianext' => 'transferencia_cabs#create', as: :newTransferenciaCab
  get '/Mensaje' => 'transferencia_cabs#mensaje'

  #Solicitudes
  get '/listadesolicitudes' => 'solicitudes#index'
  delete 'solicitud/:id' => 'solicitudes#destroy'
  patch '/transferenciaUpdate' => 'solicitudes#update', as: :updateTransferencia

  root 'sessions#new'
end

app/models/empleado.rb
class Empleado < ApplicationRecord
  has_many :transferencia_cabs
  validates :CodigoEmpleado, presence: {message: 'No puede dejarse Vacio'}
  validates :Nombre, presence: {message: 'No puede dejarse Vacio'}
  validates :Apellido, presence: {message: 'No puede dejarse Vacio'}
  validates :Departamento, presence: {message: 'No puede dejarse Vacio'}
  validates :Puesto, presence: {message: 'No puede dejarse Vacio'}

  validates :CodigoEmpleado, numericality: {message: 'Este campo debe ser numerico'}
end

app/controllers/empleados_controller.rb
class EmpleadosController < ApplicationController
  before_action :requiere_usuario_admin, only: [:index,:show, :edit,:update,:create,:new]
  def index
    @empleados = Empleado.all
  end

  def show
    @empleado =Empleado.find(params[:id])
  end

  def edit
    @empleado =Empleado.find(params[:id])
  end

  def update
    @empleado =Empleado.find(params[:id])
    if @empleado.update(params_empleado_edit)
      redirect_to '/empleados', flash: {notice: 'Datos actualizados correctamente'}
    else
      render 'edit'
    end

  end

  def new
    @empleado =Empleado.new
  end

  def create
    @empleado = Empleado.new(params_empleado)
    if @empleado.save
      redirect_to '/empleados', flash: {notice2: 'Empleado creado exitosamente'}
    else
      render 'new'
    end
  end

  def destroy
    @empleado = Empleado.find(params[:id])
    if @empleado.destroy
      redirect_to '/empleados',flash: { notice3: 'Empleado eliminado correctamente '}
    else
      redirect_to '/empleados',flash: { notice: 'Empleado no pudo ser eliminado'}
    end
  end


  private

  def params_empleado
    params.require(:empleado).permit(:CodigoEmpleado,:Nombre,:Apellido,:Departamento,:Puesto)
  end

  def params_empleado_edit
    params.require(:empleado).permit(:Nombre,:Apellido,:Departamento,:Puesto)
  end

end

app/helpers/empleados_helper.rb
module EmpleadosHelper
end

app/views/empleados/edit.html.erb
<nav class="sidebar-navigation">
  <ul>
    <%=link_to empleados_path do %>
      <li class="active">
        <i class="fa fa-users" aria-hidden="true"></i>
        <span class="tooltip">Lista de Empleados</span>
      </li>
    <%end %>

    <%=link_to productos_path do %>
      <li >
        <i class="fa fa-folder-open " aria-hidden="true"></i>
        <span class="tooltip">Lista de Productos </span>
      </li>
    <%end %>


    <%=link_to empleados_path do %>
      <li >
        <i class="fa fa-address-book-o" aria-hidden="true"></i>
        <span class="tooltip">Lista de Usuarios </span>
      </li>
    <%end %>

    <%=link_to empleados_path do %>
      <li >
        <i class="fa fa-pie-chart" aria-hidden="true"></i>
        <span class="tooltip">Reportes </span>
      </li>
    <%end %>
  </ul>
</nav>

<header class="header-nav">
  <div class="perfil">
    <p class="parrafo"><strong>Bienvenido :  </strong><%=current_user.userCompleto%></p>
    <span class="perfil--close"> <%=link_to 'Cerrar sesion',  logout_path, method: :delete,class: 'link' %></span>
  </div>
</header>


<div class="container">
  <div class="mt-5 registro">

    <h1 class="title-h1">Actualizar Empleado</h1>

    <%= form_for  @empleado, url: updateEmpleado_path(@empleado) do |f| %>
      <% if @empleado.errors.any? %>
        <div id="errorExplanation">
          <ul>
            <% @empleado.errors.full_messages.each do |msg| %>
              <li  class="alert alert-danger" role="alert" ><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="control-group error formNewEmpl mt-4">
        <div class="controls ">
          <%= f.text_field :CodigoEmpleado, :placeholder => 'Codigo Empleado',:class=>"form-control inputt",disabled: true%>
          <%= f.text_field :Nombre , :placeholder => 'Nombre',:class=>"form-control inputt"%>
        </div>

        <div class="controls">
          <%= f.text_field :Apellido, :placeholder => 'Apellido',:class=>"form-control inputt"%>
        </div>
        <div>
          <%= f.text_field :Departamento, :placeholder => 'Departamento',:class=>"form-control inputt" %>

        </div>
        <div>
          <%= f.text_field :Puesto, :placeholder => 'Puesto',:class=>"form-control inputt" %>

        </div>
        <div class="actions"><%= f.submit 'Enviar', :class=>'btn btn-success btn2' %></div>
      </div>

    <% end %>
  </div>
</div>

app/views/empleados/index.html.erb
<nav class="sidebar-navigation">
  <ul>
    <%=link_to empleados_path do %>
      <li class="active">
        <i class="fa fa-users" aria-hidden="true"></i>
        <span class="tooltip">Lista de Empleados</span>
      </li>
    <%end %>

    <%=link_to productos_path do %>
      <li >
        <i class="fa fa-folder-open " aria-hidden="true"></i>
        <span class="tooltip">Lista de Productos </span>
      </li>
    <%end %>


    <%=link_to empleados_path do %>
      <li >
        <i class="fa fa-address-book-o" aria-hidden="true"></i>
        <span class="tooltip">Lista de Usuarios </span>
      </li>
    <%end %>

    <%=link_to empleados_path do %>
      <li >
        <i class="fa fa-pie-chart" aria-hidden="true"></i>
        <span class="tooltip">Reportes </span>
      </li>
    <%end %>
  </ul>
</nav>

<header class="header-nav">
  <div class="perfil">
    <p class="parrafo"><strong>Bienvenido :  </strong><%=current_user.userCompleto%></p>
    <span class="perfil--close"> <%=link_to 'Cerrar sesion',  logout_path, method: :delete,class: 'link' %></span>
  </div>
</header>

<div class="container--box">
<header class="header-title">
  <h1>Empleados</h1>
</header>

<% if @empleados.empty? %>
  <h2>No hay empleado registrado aun....<%= link_to 'Nuevo Empleado',newEmpleado_path, class: "btn btn-primary" %> </h2>

  <%else %>
<div class="container--tableEmpl">
  <div>
    <%= link_to 'Nuevo Empleado',newEmpleado_path, class: "btn btn-primary" %>
  </div>
<table class="ui very basic collapsing celled table table--empl">
  <thead>
  <tr>
    <th>Codigo</th>
    <th>Nombre</th>
    <th>Cargo</th>
    <th>Departamento</th>
    <th>Accion</th>
  </tr></thead>
  <tbody>
  <%@empleados.each do |e| %>
  <tr>
    <td>
      <%=e.CodigoEmpleado %>
    </td>
    <td>
     <%=e.Nombre %> <%=e.Apellido %>
    </td>
  <td><%=e.Puesto %></td>
    <td> <%=e.Departamento %></td>
    <td colspan="5">
      <%= link_to 'Editar',editEmpleado_path(e), class: "btn btn-warning" %>
      <%= link_to 'Eliminar', { action: :destroy, id: e.id }, method: :delete, class: "btn btn-danger",data: {confirm: "Esta seguro de eliminar este empleado"} %>
    </td>
  </tr>
    <%end %>
  </tbody>
</table>
</div>
<%end %>
</div>
<%if flash[:notice]%>
  <div class="alert alert-info" style="float: right; margin-right: 500px">

    <p><%= flash[:notice]%></p>

  </div>
<%end %>

<%if flash[:notice2]%>
  <div class="alert alert-success" style="float: right; margin-right: 500px">

    <p><%= flash[:notice2]%></p>

  </div>
<%end %>

<%if flash[:notice3]%>
  <div class="alert alert-success" style="float: right; margin-right: 500px">

    <p><%= flash[:notice3]%></p>

  </div>
<%end %>

app/views/empleados/new.html.erb
<nav class="sidebar-navigation">
  <ul>
    <%=link_to empleados_path do %>
    <li class="active">
      <i class="fa fa-users" aria-hidden="true"></i>
      <span class="tooltip">Lista de Empleados</span>
    </li>
    <%end %>

    <%=link_to productos_path do %>
      <li >
        <i class="fa fa-folder-open " aria-hidden="true"></i>
        <span class="tooltip">Lista de Productos </span>
      </li>
    <%end %>

    <%=link_to empleados_path do %>
      <li >
        <i class="fa fa-address-book-o" aria-hidden="true"></i>
        <span class="tooltip">Lista de Usuarios </span>
      </li>
    <%end %>

    <%=link_to empleados_path do %>
      <li >
        <i class="fa fa-pie-chart" aria-hidden="true"></i>
        <span class="tooltip">Reportes </span>
      </li>
    <%end %>
  </ul>
</nav>

<header class="header-nav">
  <div class="perfil">
    <p class="parrafo"><strong>Bienvenido :  </strong><%=current_user.userCompleto%></p>
    <span class="perfil--close"> <%=link_to 'Cerrar sesion',  logout_path, method: :delete,class: 'link' %></span>
  </div>
</header>

<div class="container container--newEmpl">
  <div class="mt-5 registro">
    <h1 class="title-h1">Registro de Nuevo Empleado</h1>

    <%= form_for  @empleado, url: new_empleado_path(@empleado) do |f| %>
      <div class="control-group error formNewEmpl mt-4">
        <div class="controls">
          <%= f.text_field :CodigoEmpleado, :placeholder => 'Codigo Empleado',:class=>"form-control inputt"%>
          <%= f.text_field :Nombre , :placeholder => 'Nombre',:class=>"form-control inputt"%>
        </div>
        <div class="controls">
          <%= f.text_field :Apellido, :placeholder => 'Apellido',:class=>"form-control inputt"%>
        </div>
        <div>
          <%= f.text_field :Departamento, :placeholder => 'Departamento',:class=>"form-control inputt" %>

        </div>
        <div>
          <%= f.text_field :Puesto, :placeholder => 'Puesto',:class=>"form-control inputt" %>
        </div>
        <div><%= f.submit 'Enviar', :class=>'btn btn-success' %></div>
      </div>
      <div>
        <% if @empleado.errors.any? %>
          <div id="errorExplanation">
            <ul>
              <% @empleado.errors.full_messages.each do |msg| %>
                <li  class="alert alert-danger" role="alert" ><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>