config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #
  # Rutas para usuario
  get '/empleados' => 'empleados#index'
  get '/new/empleado' => 'empleados#new', as: :newEmpleado
  post '/new/empleado' => 'empleados#create'
  delete 'empleado/:id' => 'empleados#destroy', as: :delete
  get 'empleado/:id/edit' => 'empleados#edit', as: :editEmpleado
  patch 'empleado/:id/update' => 'empleados#update', as: :updateEmpleado

  #Rutas para producto
  get '/productos' => 'productos#index'
  get '/new/producto' => 'productos#new', as: :newProducto
  post '/new/producto' => 'productos#create'
  delete 'producto/:id' => 'productos#destroy', as: :deleteProducto
  get 'producto/:id/edit' => 'productos#edit', as: :editProducto
  patch 'producto/:id/update' => 'productos#update', as: :updateProducto

  #Ruta de Sessiones
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  #Manejo de la Cabecera para Transaccion
  get '/transferencia' => 'transferencia_cabs#new'
  get '/transferencianext' =>'transferencia_cabs#seleccion'
  post '/transferencianext' => 'transferencia_cabs#create', as: :newTransferenciaCab
  get '/Mensaje' => 'transferencia_cabs#mensaje'

  #Solicitudes
  get '/listadesolicitudes' => 'solicitudes#index'
  delete 'solicitud/:id' => 'solicitudes#destroy'
  patch '/transferenciaUpdate' => 'solicitudes#update', as: :updateTransferencia

  root 'sessions#new'
end

app/models/producto.rb
class Producto < ApplicationRecord

  validates :Serial, presence: {message: 'No puede dejarse Vacio'}
  validates :Descripcion, presence: {message: 'No puede dejarse Vacio'}
  validates :Marca, presence: {message: 'No puede dejarse Vacio'}
  validates :Modelo, presence: {message: 'No puede dejarse Vacio'}


end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_action :requiere_usuario_admin, only: [:index,:show, :edit,:update,:create,:new]

  def index
    @productos = Producto.all
  end
  def show
    @producto =Producto.find(params[:id])
  end

  def edit
    @producto =Producto.find(params[:id])
  end

  def update
    @producto =Producto.find(params[:id])
    if @producto.update(params_producto_edit)
      redirect_to '/productos', flash: {notice: 'Datos actualizados correctamente'}
    else
      render 'edit'
    end

  end

  def new
    @producto =Producto.new
  end

  def create
    @producto = Producto.new(params_producto)
    if @producto.save
      redirect_to '/productos', flash: {notice2: 'Producto creado exitosamente'}
    else
      render 'new'
    end
  end

  def destroy
    @producto = Producto.find(params[:id])
    if @producto.destroy
      redirect_to '/productos',flash: { notice3: 'Producto eliminado correctamente '}
    else
      redirect_to '/productos',flash: { notice4: 'Producto no pudo ser eliminado'}
    end
  end


  private

  def params_producto
    params.require(:producto).permit(:Serial,:Descripcion,:Marca,:Modelo,:Area)
  end

  def params_producto_edit
    params.require(:producto).permit(:Descripcion,:Marca,:Modelo,:Area)
  end
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/views/productos/edit.html.erb
<nav class="sidebar-navigation">
  <ul>
    <%=link_to empleados_path do %>
      <li >
        <i class="fa fa-users" aria-hidden="true"></i>
        <span class="tooltip">Lista de Empleados</span>
      </li>
    <%end %>

    <%=link_to productos_path do %>
      <li class="active" >
        <i class="fa fa-folder-open " aria-hidden="true"></i>
        <span class="tooltip">Lista de Productos </span>
      </li>
    <%end %>


    <%=link_to empleados_path do %>
      <li >
        <i class="fa fa-address-book-o" aria-hidden="true"></i>
        <span class="tooltip">Lista de Usuarios </span>
      </li>
    <%end %>

    <%=link_to empleados_path do %>
      <li >
        <i class="fa fa-pie-chart" aria-hidden="true"></i>
        <span class="tooltip">Reportes </span>
      </li>
    <%end %>
  </ul>
</nav>

<header class="header-nav">
  <div class="perfil">
    <p class="parrafo"><strong>Bienvenido :  </strong><%=current_user.userCompleto%></p>
    <span class="perfil--close"> <%=link_to 'Cerrar sesion',  logout_path, method: :delete,class: 'link' %></span>
  </div>
</header>


<div class="container container--newEmpl">
  <div class="mt-5 registro">

    <h1 class="title-h1">Actualizar Producto</h1>

    <%= form_for  @producto, url: updateProducto_path(@producto) do |f| %>
      <% if @producto.errors.any? %>
        <div id="errorExplanation">
          <ul>
            <% @producto.errors.full_messages.each do |msg| %>
              <li  class="alert alert-danger" role="alert" ><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="control-group error formNewEmpl mt-4">
        <div class="controls ">
          <%= f.text_field :Serial, :placeholder => 'Serial',:class=>"form-control inputt",disabled: true%>
          <%= f.text_field :Descripcion , :placeholder => 'Descripcion',:class=>"form-control inputt"%>
        </div>
        <div class="controls">
          <%= f.text_field :Marca, :placeholder => 'Marca',:class=>"form-control inputt"%>
        </div>
        <div>
          <%= f.text_field :Modelo, :placeholder => 'Modelo',:class=>"form-control inputt" %>

        </div>
        <div>
          <%= f.text_field :Area, :placeholder => 'Area',:class=>"form-control inputt" %>

        </div>
        <div class="actions"><%= f.submit 'Enviar', :class=>'btn btn-success btn2' %></div>
      </div>
    <% end %>
  </div>
</div>

app/views/productos/index.html.erb
<nav class="sidebar-navigation">
  <ul>
    <%=link_to empleados_path do %>
      <li >
        <i class="fa fa-users" aria-hidden="true"></i>
        <span class="tooltip">Lista de Empleados</span>
      </li>
    <%end %>

    <%=link_to productos_path do %>
      <li class="active" >
        <i class="fa fa-folder-open " aria-hidden="true"></i>
        <span class="tooltip">Lista de Productos </span>
      </li>
    <%end %>


    <%=link_to empleados_path do %>
      <li >
        <i class="fa fa-address-book-o" aria-hidden="true"></i>
        <span class="tooltip">Lista de Usuarios </span>
      </li>
    <%end %>

    <%=link_to empleados_path do %>
      <li >
        <i class="fa fa-pie-chart" aria-hidden="true"></i>
        <span class="tooltip">Reportes </span>
      </li>
    <%end %>
  </ul>
</nav>

<header class="header-nav">
  <div class="perfil">
    <p class="parrafo"><strong>Bienvenido :  </strong><%=current_user.userCompleto%></p>
    <span class="perfil--close"> <%=link_to 'Cerrar sesion',  logout_path, method: :delete,class: 'link' %></span>
  </div>
</header>


<div class="container--box">
  <header class="header-title">
    <h1>Productos</h1>
  </header>
<% if @productos.empty? %>
  <h2>No hay produtos registrado aun....<%= link_to 'Nuevo Producto',newProducto_path, class: "btn btn-primary" %> </h2>



<%else %>
  <div class="container--tableEmpl">
    <div>
      <%= link_to 'Nuevo Producto',newProducto_path, class: "btn btn-primary" %>
    </div>
    <table class="ui very basic collapsing celled table table--empl">
      <thead>
      <tr>
        <th>Serial</th>
        <th>Productos</th>
        <th>Model</th>
        <th>Area</th>
        <th>Accion</th>
      </tr></thead>
      <tbody>
      <%@productos.each do |e| %>
        <tr>
          <td><%=e.Serial %></td>
          <td><%=e.Descripcion %> <%=e.Marca %></td>
          <td><%=e.Modelo %></td>
          <td><%=e.Area %></td>
          <td colspan="3">
            <%= link_to 'Editar',editProducto_path(e), class: "btn btn-warning" %>
            <%= link_to 'Eliminar', { action: :destroy, id: e.id }, method: :delete, class: "btn btn-danger",data: {confirm: "Esta seguro de eliminar este producto"} %>
          </td>
        </tr>
      <%end %>
      </tbody>
    </table>
  </div>
<%end %>
</div>
<%if flash[:notice]%>
  <div class="alert alert-info" style="float: right; margin-right: 500px">

    <p><%= flash[:notice]%></p>

  </div>
<%end %>

<%if flash[:notice2]%>
  <div class="alert alert-success" style="float: right; margin-right: 500px">

    <p><%= flash[:notice2]%></p>

  </div>
<%end %>

<%if flash[:notice3]%>
  <div class="alert alert-success" style="float: right; margin-right: 500px">

    <p><%= flash[:notice3]%></p>

  </div>
<%end %>

app/views/productos/new.html.erb
<nav class="sidebar-navigation">
  <ul>
    <%=link_to empleados_path do %>
      <li >
        <i class="fa fa-users" aria-hidden="true"></i>
        <span class="tooltip">Lista de Empleados</span>
      </li>
    <%end %>

    <%=link_to productos_path do %>
      <li class="active" >
        <i class="fa fa-folder-open " aria-hidden="true"></i>
        <span class="tooltip">Lista de Productos </span>
      </li>
    <%end %>

    <%=link_to empleados_path do %>
      <li >
        <i class="fa fa-address-book-o" aria-hidden="true"></i>
        <span class="tooltip">Lista de Usuarios </span>
      </li>
    <%end %>

    <%=link_to empleados_path do %>
      <li >
        <i class="fa fa-pie-chart" aria-hidden="true"></i>
        <span class="tooltip">Reportes </span>
      </li>
    <%end %>
  </ul>
</nav>

<header class="header-nav">
  <div class="perfil">
    <p class="parrafo"><strong>Bienvenido :  </strong><%=current_user.userCompleto%></p>
    <span class="perfil--close"> <%=link_to 'Cerrar sesion',  logout_path, method: :delete,class: 'link' %></span>
  </div>
</header>

<div class="container container--newEmpl">
  <div class="mt-5 registro">

    <h1 class="title-h1">Registro de Nuevo Producto</h1>

    <%= form_for  @producto, url: new_producto_path(@producto) do |f| %>
      <% if @producto.errors.any? %>
        <div id="errorExplanation">
          <ul>
            <% @producto.errors.full_messages.each do |msg| %>
              <li  class="alert alert-danger" role="alert" ><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="control-group error formNewEmpl mt-4">
        <div class="controls ">
          <%= f.text_field :Serial, :placeholder => 'Serial',:class=>"form-control inputt"%>
          <%= f.text_field :Descripcion , :placeholder => 'Descripcion',:class=>"form-control inputt"%>
        </div>
        <div class="controls">
          <%= f.text_field :Marca, :placeholder => 'Marca',:class=>"form-control inputt"%>
        </div>
        <div>
          <%= f.text_field :Modelo, :placeholder => 'Modelo',:class=>"form-control inputt" %>

        </div>
        <div>
          <%= f.text_field :Area, :placeholder => 'Area',:class=>"form-control inputt" %>

        </div>
        <div class="actions"><%= f.submit 'Enviar', :class=>'btn btn-success btn2' %></div>
      </div>

    <% end %>
  </div>
</div>