config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #
  # Rutas para usuario
  get '/empleados' => 'empleados#index'
  get '/new/empleado' => 'empleados#new', as: :newEmpleado
  post '/new/empleado' => 'empleados#create'
  delete 'empleado/:id' => 'empleados#destroy', as: :delete
  get 'empleado/:id/edit' => 'empleados#edit', as: :editEmpleado
  patch 'empleado/:id/update' => 'empleados#update', as: :updateEmpleado

  #Rutas para producto
  get '/productos' => 'productos#index'
  get '/new/producto' => 'productos#new', as: :newProducto
  post '/new/producto' => 'productos#create'
  delete 'producto/:id' => 'productos#destroy', as: :deleteProducto
  get 'producto/:id/edit' => 'productos#edit', as: :editProducto
  patch 'producto/:id/update' => 'productos#update', as: :updateProducto

  #Ruta de Sessiones
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  #Manejo de la Cabecera para Transaccion
  get '/transferencia' => 'transferencia_cabs#new'
  get '/transferencianext' =>'transferencia_cabs#seleccion'
  post '/transferencianext' => 'transferencia_cabs#create', as: :newTransferenciaCab
  get '/Mensaje' => 'transferencia_cabs#mensaje'

  #Solicitudes
  get '/listadesolicitudes' => 'solicitudes#index'
  delete 'solicitud/:id' => 'solicitudes#destroy'
  patch '/transferenciaUpdate' => 'solicitudes#update', as: :updateTransferencia

  root 'sessions#new'
end

app/models/transferencia_cab.rb
class TransferenciaCab < ApplicationRecord
  belongs_to :empleado
end

app/controllers/transferencia_cabs_controller.rb
class TransferenciaCabsController < ApplicationController
  def new
    begin
      if params[:codigo].present?
        @empleado =Empleado.find_by_CodigoEmpleado(params[:codigo])
      else

      end
    rescue
      redirect_to transferencia_path, flash: {notice: "Registro no encontrado"}
    end
  end

  def mensaje

  end

  def seleccion
    @empleado =Empleado.find_by_CodigoEmpleado(params[:codigo])
    @cabeceraTrans = TransferenciaCab.new
  end

  def create


    if params[:commit] =='Recibir Ruta de Soporte Correctivo'
      params[:Servicio] ='Recibir Ruta de Soporte Correctivo'
      @empleado =Empleado.find_by_CodigoEmpleado(params[:codigo])
      @cabeceraTrans = TransferenciaCab.new(params_cabecera )
      if @cabeceraTrans.save
        redirect_to '/Mensaje'
      else
        render 'seleccion'
      end
    elsif  params[:commit] =='Recibir Ruta de Mantenimiento Preventivo'
      params[:Servicio] ='Recibir Ruta de Mantenimiento Preventivo'
      @empleado =Empleado.find_by_CodigoEmpleado(params[:codigo])
      @cabeceraTrans = TransferenciaCab.new(params_cabecera)
      if @cabeceraTrans.save
        redirect_to '/Mensaje'
      else
        render 'seleccion'
      end
    end


  end

  private
  def params_cabecera
    params.require(:transferencia_cab).permit(:empleados_id,:empleado_id,:Servicio, :Tiempo)
  end
end

app/helpers/transferencia_cabs_helper.rb
module TransferenciaCabsHelper
end

app/views/transferencia_cabs/mensaje.html.erb
<div class="formularioCab">
  <div class="form--containerCode--text">





    <p class="toCab">Por favor dirigirse a donde su supervisos, gracias.</p>





  </div>
</div>

app/views/transferencia_cabs/new.html.erb
<div class="formularioCab">

  <%= form_tag transferencia_path,method: :get , class:'cont form--containerCode', name:'calculator' do%>
    <div class="form--containerCode--text">
     <p class="toCab">Toner Deport</p>
     <p class="toCab1">Ingresar su código de empleado </p>
    </div>
    <div class="inputCont">
      <div class="form--containerCode-input">
       <%= text_field_tag :codigo, nil,placeholder: '12345678',:class=>'form-control inputcab', value:"" %>
      </div>
      <div class="">
        <div>
          <input type="button"  class="btn btnCal " value="1" onclick="document.calculator.codigo.value+='1'">
          <input type="button"  class="btn btnCal" value="2" onclick="document.calculator.codigo.value+='2'">
          <input type="button"  class="btn btnCal " value="3" onclick="document.calculator.codigo.value+='3'">
        </div>

        <div>
          <input type="button"  class="btn btnCal" value="4" onclick="document.calculator.codigo.value+='4'">
          <input type="button"  class="btn btnCal" value="5" onclick="document.calculator.codigo.value+='5'">
          <input type="button"  class="btn btnCal" value="6" onclick="document.calculator.codigo.value+='6'">
        </div>

        <div>
          <input type="button"  class="btn btnCal" value="7" onclick="document.calculator.codigo.value+='7'">
          <input type="button"  class="btn btnCal" value="8" onclick="document.calculator.codigo.value+='8'">
          <input type="button"  class="btn btnCal" value="9" onclick="document.calculator.codigo.value+='9'">
        </div>

        <div>
          <input type="button"  class="btn btnCal" value="0" onclick="document.calculator.codigo.value+='0'">
          <input type="reset"  class="btn btnCal" value="C" >
          <input type="button"  class="btn btnCal" value="←" onclick="document.calculator.codigo.value= document.calculator.codigo.value.substring(0,document.calculator.codigo.value.length - 1)">
        </div>
      </div>

    </div>
    <div>
      <%= submit_tag 'Buscar' ,class: ''%>


  <%end%>

  <%if @empleado.present? %>
    <p class="toCab"><strong>Empleado: </strong>  <%= @empleado.Nombre  %> <%=@empleado.Apellido %>  </p>
    <button class="btn btn-info " style="text-align: center"><%=link_to 'Continuar',transferencianext_path(:codigo => @empleado.CodigoEmpleado) %></button>
  <%end %>


  <%if flash[:notice]%>
    <div class="alerta2 alert alert-danger" style="margin-left: 10px;margin-right: 10px;font-weight: bold">

      <p><%=flash[:notice]%></p>
  <%end%>
    </div>


  </div>
</div>




</div>

app/views/transferencia_cabs/seleccion.html.erb
<div class="formularioCab">
  <div class="form--containerCode--text">
    <p class="toCab">Toner Deport</p>
    <p class="toCab1">Seleccione el Servicio </p>

  <%= form_for  @cabeceraTrans, url: newTransferenciaCab_path(@cabeceraTrans) do |f| %>

      <%=f.hidden_field :empleados_id, value: @empleado.id %>
      <%=f.hidden_field :empleado_id, value: @empleado.id %>
      <%=f.hidden_field :Servicio, value: 'Recibir Ruta de Soporte Correctivo'%>
      <%=f.hidden_field :Tiempo, value: '0'  %>
      <%=f.submit 'Recibir Ruta de Soporte Correctivo' %>
      <%=f.submit 'Recibir Ruta de Mantenimiento Preventivo' %>
  <%end %>




  </div>
</div>